# Agenda

1. NumPy
2. Pandas series
3. Data frames
4. Indexes, sorting, grouping
5. Dates and times
6. Optimtizing speed +memory
7. 

In [1]:
x = 0

import sys
sys.getsizeof(x)

28

In [2]:
x = 123_456_789 ** 100

In [3]:
type(x)

int

In [4]:
sys.getsizeof(x)

384

In [5]:
import numpy as np

In [6]:
a = np.array([10, 20, 30])

In [7]:
a

array([10, 20, 30])

In [8]:
type(a)

numpy.ndarray

In [9]:
a[0]

10

In [10]:
type(a[0])

numpy.int64

In [11]:
# methods

a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

In [12]:
a.mean()

45.0

In [13]:
a.std()

22.9128784747792

In [14]:
a.min()

10

In [15]:
a.max()

80

In [16]:
a.sum()

360

In [17]:
np.mean(a)

45.0

In [18]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [19]:
mylist1 = [10, 20,30]
mylist2 = [40, 50, 60]

mylist1 + 3

TypeError: can only concatenate list (not "int") to list

In [20]:
mylist1 + mylist2

[10, 20, 30, 40, 50, 60]

In [21]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [22]:
# broadcasting 
a + 3

array([13, 23, 33, 43, 53, 63, 73, 83])

In [23]:
a ** 2

array([ 100,  400,  900, 1600, 2500, 3600, 4900, 6400])

In [24]:
a / 4   # truediv -- floats are returned, even from ints

array([ 2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [25]:
a // 4   # floordiv -- returns ints, truncating the fractional part

array([ 2,  5,  7, 10, 12, 15, 17, 20])

In [26]:
type((a/4)[0])

numpy.float64

In [27]:
a.size

8

In [28]:
sys.getsizeof(a)

176

In [29]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [30]:
a + a

array([ 20,  40,  60,  80, 100, 120, 140, 160])

In [31]:
a + a*2

array([ 30,  60,  90, 120, 150, 180, 210, 240])

In [32]:
b = np.array([100, 200, 300])

a + b

ValueError: operands could not be broadcast together with shapes (8,) (3,) 

In [33]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [34]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [35]:
a[2] = 999
a

array([ 10,  20, 999,  40,  50,  60,  70,  80])

In [36]:
a.dtype 

dtype('int64')

In [37]:
a[2] = 123.456

In [38]:
a

array([ 10,  20, 123,  40,  50,  60,  70,  80])

In [39]:
a[3] = '456'

In [40]:
a

array([ 10,  20, 123, 456,  50,  60,  70,  80])

In [41]:
a[4] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [42]:
# type -- Python type (NumPy array, str, int, float, etc.)
# dtype -- the NumPy type that is used in the array

In [43]:
a.dtype

dtype('int64')

In [44]:
# other ways to create NumPy arrays

a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a = np.arange(0, 20, 3)
a

array([ 0,  3,  6,  9, 12, 15, 18])

In [46]:
# random ints
np.random.randint(0, 100, 10)   # 10 random ints from 0-100

array([98, 61, 34, 77, 43, 84, 55, 12, 42, 83])

In [47]:
# random floats
np.random.rand(10)  # returns 10 floats between 0-1

array([0.94026983, 0.00864543, 0.18218215, 0.41555072, 0.3276063 ,
       0.97107167, 0.76853173, 0.61133973, 0.90086217, 0.06216901])

In [48]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Exercise: Simple NumPy arrays

1. Create a 3-element NumPy array with your birthday.
2. Change the year to be this year.
3. What is the type of the array? What is the dtype of the array? What is the type of the year?
4. Create an array with 10 random ints from 0-100.
5. Find the mean and std of these numbers.
6. Create an array of 10 random floats from 0-100.
7. Find the mean and std. Are they similar to the ints?

GitHub repo to see my Jupyter notebook:

https://github.com/reuven/apple-2024-q4-data